spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/person?characterEncoding=UTF-8
    username: root
    password: luxiao0314

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

spring.jackson.serialization.write-dates-as-timestamps: true

# 默认的 8080 我们将它改成 9090
server.port: 9090
# 未定义上下文路径之前 地址是 http://localhost:8080 定义了后 http://localhost:9090 你能在tomcat做的事情，配置文件都可以
#server.servlet.context-path: /